#!/bin/sh

export MONITOR=$(polybar -m|tail -1|sed -e 's/:.*$//g')

picom -C &
sxhkd &
wal -R &
wmname LG3D &
polybar top &
xsetroot -cursor_name left_ptr

bspc monitor HDMI1 -d 1 2 3 4 5

bspc config focus_follows_pointer on
bspc config window_gap 4


. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
