#!/bin/sh

sxhkd &
xrandr --dpi 96
xsetroot -cursor_name left_ptr &
killall -q polybar; polybar top &
picom -C --no-fading-openclose -I 1 -O 1 &
wmname LG3D &

bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer on
bspc config window_gap 4
bspc config border_width 2

bspc config focused_border_color "#83a598"
bspc config normal_border_color "#1d2021"
bspc config urgent_border_color "#fb4934"
bspc config presel_border_color "#a89984"
